#scale=ewa_lanczossharp
#cscale=ewa_lanczossharp
hwdec=auto-safe
profile=gpu-hq
#icc-profile-auto
blend-subtitles=video
video-sync=display-resample
interpolation
tscale=oversample
sub-auto=fuzzy
fs
volume=50
autofit-larger=100%x95%
audio-file-auto=fuzzy

