--enable-features=DisableQRGenerator,EncryptedClientHello,UseDnsHttpsSvcbAlpn,VaapiVideoDecodeLinuxGL,TouchpadOverscrollHistoryNavigation
--disable-features=WaylandFractionalScaleV1,ChromeLabs
--ozone-platform-hint=auto
--gtk-version=4
--bookmark-bar-ntp=never
--disable-beforeunload
--disable-search-engine-collection
--disable-sharing-hub
--disable-top-sites
--extension-mime-request-handling=always-prompt-for-install
--hide-crashed-bubble
--hide-fullscreen-exit-ui
--hide-sidepanel-button
--hide-tab-close-buttons
--keep-old-history
--max-connections-per-host=15
--no-pings
--remove-tabsearch-button
--show-avatar-button=incognito-and-guest
--enable-smooth-scrolling
--tab-hover-cards=none
